name: arptool
on: [push, pull_request]

jobs:
  build-ubuntu:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.ACCESS_TOKEN}}
        submodules: recursive
    - name: Configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
    - name: Build
      run: cmake --build build --parallel 8
    - name: Archive
      uses: actions/upload-artifact@v1
      with:
        name: arptool_dist_linux
        path: build/arptool

  build-windows:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.ACCESS_TOKEN}}
        submodules: recursive
    - name: Configure
      run: mkdir build && cd build && cmake -DCMAKE_SYSTEM_VERSION=10.0.19041.0 -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_BUILD_TYPE=Debug ..
    - name: Build
      run: cmake --build build --parallel 8
    - name: Archive
      uses: actions/upload-artifact@v1
      with:
        name: arptool_dist_windows
        path: build/Debug/arptool.exe
